# Generated by Django 4.2.11 on 2025-02-01 15:25

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='OpenDemand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ctool_number', models.CharField(max_length=50, unique=True)),
                ('ctool_date', models.DateField()),
                ('client_manager_name', models.CharField(max_length=100)),
                ('client_location', models.CharField(max_length=100)),
                ('position_location', models.CharField(max_length=100)),
                ('tentative_required_by', models.DateField()),
                ('skillset', models.TextField(max_length=500)),
                ('lob_name', models.CharField(max_length=100)),
                ('practice_unit_name', models.CharField(max_length=100)),
                ('job_description', models.FileField(upload_to='job_descriptions/')),
                ('no_of_positions', models.IntegerField()),
                ('rr_numbers', models.CharField(max_length=100)),
                ('rr_grade', models.CharField(max_length=50)),
                ('gcb_level', models.CharField(max_length=50)),
            ],
        ),
    ]
