# Generated by Django 4.2.11 on 2025-02-09 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='emp_updateby',
            field=models.IntegerField(blank=True, default=1, help_text='User ID who updated the record'),
            preserve_default=False,
        ),
    ]
