# Generated by Django 4.2.11 on 2025-02-02 10:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ClientMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('client_name', models.CharField(max_length=50)),
                ('client_manager_name', models.CharField(max_length=50)),
                ('client_email', models.EmailField(max_length=254)),
                ('client_phone', models.CharField(max_length=15)),
                ('client_location', models.CharField(max_length=100)),
                ('client_department', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LOBMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lob_name', models.CharField(max_length=100)),
                ('lob_delivery_manager', models.CharField(max_length=100)),
                ('lob_client_partner', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='LocationMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location_name', models.CharField(max_length=100)),
                ('state', models.CharField(max_length=100)),
                ('country', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='PracticeUnitMaster',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('practice_unit_name', models.CharField(max_length=100)),
                ('practice_unit_sales', models.CharField(max_length=100)),
                ('practice_unit_delivery', models.CharField(max_length=100)),
                ('practice_unit_solution', models.CharField(max_length=100)),
            ],
        ),
    ]
