# Generated by Django 4.2.11 on 2025-02-10 06:38

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0003_delete_strategicbusinessunitmaster_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='candidatemaster',
            old_name='cdm_updatedby',
            new_name='cdm_updateby',
        ),
        migrations.RenameField(
            model_name='candidatestatusmaster',
            old_name='csm_insertedby',
            new_name='csm_insertby',
        ),
        migrations.RenameField(
            model_name='clientmanagermaster',
            old_name='cmm_insertedby',
            new_name='cmm_insertby',
        ),
        migrations.RenameField(
            model_name='clientmanagermaster',
            old_name='cmm_updatedby',
            new_name='cmm_updateby',
        ),
        migrations.RenameField(
            model_name='demandstatusmaster',
            old_name='dsm_insertedby',
            new_name='dsm_insertby',
        ),
        migrations.RenameField(
            model_name='locationmaster',
            old_name='lcm_insertedby',
            new_name='lcm_insertby',
        ),
        migrations.RenameField(
            model_name='locationmaster',
            old_name='lcm_updatedby',
            new_name='lcm_updateby',
        ),
        migrations.RemoveField(
            model_name='clientmanagermaster',
            name='cmm_location',
        ),
        migrations.RemoveField(
            model_name='clientmaster',
            name='clm_location',
        ),
        migrations.RemoveField(
            model_name='employeemaster',
            name='emp_location',
        ),
        migrations.AddField(
            model_name='clientmanagermaster',
            name='cmm_lcm_id',
            field=models.ForeignKey(help_text='Reference to Location Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_clientmanager', to='hiringManagementTool.locationmaster'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='clm_lcm_id',
            field=models.ForeignKey(help_text='Reference to Location Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_client', to='hiringManagementTool.locationmaster'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='emp_lcm_id',
            field=models.ForeignKey(help_text='Reference to Location Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_employee', to='hiringManagementTool.locationmaster'),
        ),
        migrations.AlterField(
            model_name='candidatedemandhistory',
            name='cdh_fromdata',
            field=models.JSONField(blank=True, help_text='Old Value/Data before change', null=True),
        ),
        migrations.AlterField(
            model_name='candidatedemandhistory',
            name='cdh_todata',
            field=models.JSONField(blank=True, help_text='New Value/Data after change', null=True),
        ),
        migrations.AlterField(
            model_name='candidatemaster',
            name='cdm_location',
            field=models.ForeignKey(help_text='Reference to Location Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_candidate', to='hiringManagementTool.locationmaster'),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_insertby',
            field=models.ForeignKey(blank=True, help_text='Reference to the employee who inserted this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clm_inserted_records', to='hiringManagementTool.employeemaster'),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_updateby',
            field=models.ForeignKey(blank=True, help_text='Reference to the employee who last updated this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='clm_updated_records', to='hiringManagementTool.employeemaster'),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='emp_rlm_id',
            field=models.ForeignKey(blank=True, help_text='Role ID associated with the employee', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='role_employee', to='hiringManagementTool.rolemaster'),
        ),
    ]
