# Generated by Django 4.2.11 on 2025-02-10 16:45

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0004_rename_cdm_updatedby_candidatemaster_cdm_updateby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemaster',
            name='cdm_csm_id',
            field=models.ForeignKey(blank=True, help_text='Reference to another candidate (if applicable)', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='candidate_references', to='hiringManagementTool.candidatestatusmaster'),
        ),
    ]
