# Generated by Django 4.2.11 on 2025-02-11 05:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0006_alter_internaldepartmentmaster_idm_spoc_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='internaldepartmentmaster',
            old_name='idm_deliverymanager_id',
            new_name='idm_deliverymanager',
        ),
        migrations.RenameField(
            model_name='internaldepartmentmaster',
            old_name='idm_spoc_id',
            new_name='idm_spoc',
        ),
    ]
