# Generated by Django 4.2.11 on 2025-02-11 05:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0007_rename_idm_deliverymanager_id_internaldepartmentmaster_idm_deliverymanager_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldepartmentmaster',
            name='idm_spoc',
            field=models.ForeignKey(blank=True, help_text='Single Point of Contact (SPOC) from Employee Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_master', to='hiringManagementTool.employeemaster'),
        ),
    ]
