# Generated by Django 4.2.11 on 2025-02-11 05:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0008_alter_internaldepartmentmaster_idm_spoc'),
    ]

    operations = [
        migrations.AlterField(
            model_name='internaldepartmentmaster',
            name='idm_deliverymanager',
            field=models.ForeignKey(blank=True, db_column='idm_deliverymanager_id', help_text='Delivery Manager from Employee Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='internaldepartment_delivery_manager', to='hiringManagementTool.employeemaster'),
        ),
        migrations.RenameField(
            model_name='internaldepartmentmaster',
            old_name='idm_deliverymanager',
            new_name='idm_deliverymanager_id',
        ),
        migrations.AlterField(
            model_name='internaldepartmentmaster',
            name='idm_spoc',
            field=models.ForeignKey(blank=True, db_column='idm_spoc_id', help_text='Single Point of Contact (SPOC) from Employee Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='employee_master', to='hiringManagementTool.employeemaster'),
        ),
        migrations.RenameField(
            model_name='internaldepartmentmaster',
            old_name='idm_spoc',
            new_name='idm_spoc_id',
        ),
    ]
