# Generated by Django 4.2.11 on 2025-02-13 18:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0010_alter_candidatemaster_cdm_csm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidatedemandlink',
            name='cdl_cdm_id',
        ),
        migrations.RemoveField(
            model_name='candidatedemandlink',
            name='cdl_csm_id',
        ),
        migrations.RemoveField(
            model_name='candidatedemandlink',
            name='cdl_dem_id',
        ),
        migrations.RemoveField(
            model_name='demandhistorytable',
            name='dhs_dsm',
        ),
        migrations.DeleteModel(
            name='CandidateDemandHistory',
        ),
        migrations.DeleteModel(
            name='CandidateDemandLink',
        ),
        migrations.DeleteModel(
            name='DemandHistoryTable',
        ),
    ]
