# Generated by Django 4.2.11 on 2025-02-17 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0011_remove_candidatedemandlink_cdl_cdm_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendemand',
            name='dem_cmm_id',
        ),
    ]
