# Generated by Django 4.2.11 on 2025-02-18 10:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0013_delete_clientmanagermaster'),
    ]

    operations = [
    ]
