# Generated by Django 4.2.11 on 2025-02-18 17:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0014_auto_20250218_1615'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandstatusmaster',
            name='dsm_insertby',
            field=models.ForeignKey(db_column='dsm_insertby', help_text='User ID (Employee) who created this status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_inserted', to='hiringManagementTool.employeemaster'),
        ),
        migrations.AlterField(
            model_name='demandstatusmaster',
            name='dsm_updateby',
            field=models.ForeignKey(db_column='dsm_updateby', help_text='User ID (Employee) who last updated this status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updated', to='hiringManagementTool.employeemaster'),
        ),
        migrations.CreateModel(
            name='DemandHistory',
            fields=[
                ('dhs_id', models.AutoField(help_text='Primary Key (Auto-generated for Status History)', primary_key=True, serialize=False)),
                ('dhs_dsm_insertdate', models.DateTimeField(help_text='Status insert date (from DemandStatusMaster)')),
                ('dhs_fromdata', models.TextField(blank=True, help_text='Old value/data before update', null=True)),
                ('dhs_todata', models.TextField(blank=True, help_text='New value/data after update', null=True)),
                ('dhs_log_msg', models.TextField(blank=True, help_text='Comments regarding status change', null=True)),
                ('dhs_dem_id', models.ForeignKey(db_column='dhs_dem_id', help_text='Reference to Open demand', on_delete=django.db.models.deletion.CASCADE, related_name='open_demand', to='hiringManagementTool.opendemand')),
                ('dhs_dsm_id', models.ForeignKey(db_column='dhs_dsm_id', help_text='Reference to Demand Status Master', on_delete=django.db.models.deletion.CASCADE, related_name='demand_history', to='hiringManagementTool.demandstatusmaster')),
                ('dhs_insertby', models.ForeignKey(blank=True, db_column='dhs_insertby', help_text='User ID (Employee) who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_inserted', to='hiringManagementTool.employeemaster')),
            ],
            options={
                'db_table': 'demandhistory',
                'managed': True,
            },
        ),
    ]
