# Generated by Django 4.2.11 on 2025-02-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0016_alter_demandstatusmaster_dsm_insertby_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandstatusmaster',
            old_name='dsm_insertby',
            new_name='dsm_insertby_id',
        ),
    ]
