# Generated by Django 4.2.11 on 2025-02-18 17:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0017_rename_dsm_insertby_demandstatusmaster_dsm_insertby_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandstatusmaster',
            name='dsm_insertby_id',
        ),
    ]
