# Generated by Django 4.2.11 on 2025-02-18 15:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0017_remove_demandhistory_dhs_insterted_by_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandhistory',
            name='dhs_inserted_by',
        ),
    ]
