# Generated by Django 4.2.11 on 2025-02-18 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0018_remove_demandstatusmaster_dsm_insertby_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandstatusmaster',
            name='dsm_updateby',
        ),
    ]
