# Generated by Django 4.2.11 on 2025-02-18 15:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0018_remove_demandhistory_dhs_inserted_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandhistory',
            name='dhs_inserted_by',
            field=models.ForeignKey(blank=True, db_column='dhs_inserted_by', help_text='User ID (Employee) who created this record', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='demand_inserted', to='hiringManagementTool.employeemaster'),
        ),
    ]
