# Generated by Django 4.2.11 on 2025-02-18 15:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0019_demandhistory_dhs_inserted_by'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandhistory',
            name='dhs_inserted_by',
        ),
    ]
