# Generated by Django 4.2.11 on 2025-02-19 03:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0019_remove_demandstatusmaster_dsm_updateby'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandstatusmaster',
            name='dsm_insertby',
            field=models.ForeignKey(help_text='User ID (Employee) who created this status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_inserted', to='hiringManagementTool.employeemaster'),
        ),
        migrations.AddField(
            model_name='demandstatusmaster',
            name='dsm_updateby',
            field=models.ForeignKey(help_text='User ID (Employee) who last updated this status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updated', to='hiringManagementTool.employeemaster'),
        ),
    ]
