# Generated by Django 4.2.11 on 2025-02-19 03:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0020_demandstatusmaster_dsm_insertby_id_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandstatusmaster',
            old_name='dsm_insertby',
            new_name='dsm_insertby_id',
        ),
    ]
