# Generated by Django 4.2.11 on 2025-02-24 08:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0022_remove_demandstatusmaster_dsm_insertby_id_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandhistory',
            name='dhs_insertby',
        ),
        migrations.RemoveField(
            model_name='demandstatusmaster',
            name='dsm_insertby_id',
        ),
        migrations.AlterField(
            model_name='demandstatusmaster',
            name='dsm_updateby',
            field=models.ForeignKey(db_column='dsm_updateby', help_text='User ID (Employee) who last updated this status', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_updated', to='hiringManagementTool.employeemaster'),
        ),
        migrations.CreateModel(
            name='CandidateDemandLink',
            fields=[
                ('cdl_id', models.AutoField(help_text='Unique Candidate Demand Link ID (Auto-generated)', primary_key=True, serialize=False)),
                ('cdl_joiningdate', models.DateField(help_text='Future Joining Date of Candidate')),
                ('cdl_insertdate', models.DateTimeField(auto_now_add=True, help_text='Record Creation Timestamp')),
                ('cdl_cdm_id', models.ForeignKey(db_column='cdl_cdm_id', help_text='Reference to Candidate Master', on_delete=django.db.models.deletion.CASCADE, related_name='demand_links', to='hiringManagementTool.candidatemaster')),
                ('cdl_csm_id', models.ForeignKey(blank=True, db_column='cdl_csm_id', help_text='Reference to Candidate Status Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='linked_candidates', to='hiringManagementTool.candidatestatusmaster')),
                ('cdl_dem_id', models.ForeignKey(db_column='cdl_dem_id', help_text='Reference to Demand Table', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_links', to='hiringManagementTool.opendemand')),
            ],
            options={
                'db_table': 'candidatedemandlink',
                'managed': True,
            },
        ),
    ]
