# Generated by Django 4.2.11 on 2025-02-24 09:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0025_alter_opendemand_dem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemaster',
            name='cdm_id',
            field=models.CharField(editable=False, help_text='Auto-generated ID in format cdm_ddmmyyyy_1', max_length=50, primary_key=True, serialize=False),
        ),
    ]
