# Generated by Django 4.2.11 on 2025-02-24 12:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0026_alter_candidatemaster_cdm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemaster',
            name='cdm_id',
            field=models.CharField(db_column='cdm_id', editable=False, help_text='Auto-generated ID in format cdm_ddmmyyyy_1', max_length=50, primary_key=True, serialize=False),
        ),
    ]
