# Generated by Django 4.2.11 on 2025-02-24 13:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0027_alter_candidatemaster_cdm_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendemand',
            name='dem_id',
            field=models.CharField(editable=False, help_text='Formatted Primary Key (Auto-generated for Demand Entry) dem_ddmmyyyy_01', max_length=50, primary_key=True, serialize=False),
        ),
    ]
