# Generated by Django 4.2.11 on 2025-02-25 08:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0028_alter_opendemand_dem_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedemandlink',
            name='cdl_joiningdate',
            field=models.DateField(help_text='Future Joining Date of Candidate', null=True),
        ),
    ]
