# Generated by Django 4.2.11 on 2025-03-06 11:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0030_rename_position_name_opendemand_dem_position_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='emp_insertby',
            field=models.CharField(help_text='User ID who inserted the record (from connection table)', max_length=50),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='emp_updateby',
            field=models.CharField(blank=True, help_text='User ID who updated the record', max_length=50, null=True),
        ),
    ]
