# Generated by Django 4.2.11 on 2025-03-07 06:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0031_alter_employeemaster_emp_insertby_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatedemandlink',
            name='cdl_dem_id',
            field=models.ForeignKey(db_column='cdl_dem_id', help_text='Reference to Open Demand', on_delete=django.db.models.deletion.CASCADE, related_name='demand_links', to='hiringManagementTool.opendemand'),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_ctooldate',
            field=models.DateTimeField(blank=True, help_text='Requirement/Demand Date from Client', null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_insertdate',
            field=models.DateTimeField(auto_now_add=True, help_text='Record Creation Timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_isactive',
            field=models.BooleanField(blank=True, default=True, help_text='Indicates if Demand is Active (1 = Active, 0 = Inactive)', null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_isreopened',
            field=models.BooleanField(blank=True, default=False, help_text='Indicates if Demand is Reopened (1 = Reopened, 0 = New)', null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_positions',
            field=models.IntegerField(blank=True, help_text='Number of Positions Required', null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_rrnumber',
            field=models.CharField(blank=True, help_text='Request Number', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_skillset',
            field=models.TextField(blank=True, help_text='Multiple skillsets separated by commas', null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_updatedate',
            field=models.DateTimeField(auto_now=True, help_text='Record Last Updated Timestamp', null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_validtill',
            field=models.DateTimeField(blank=True, help_text='Requirement/Demand Closing Date', null=True),
        ),
    ]
