# Generated by Django 4.2.11 on 2025-03-07 06:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0032_alter_candidatedemandlink_cdl_dem_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendemand',
            name='dem_idm_id',
            field=models.ForeignKey(blank=True, db_column='dem_idm_id', help_text='Reference to Internal Department Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='idm_demands', to='hiringManagementTool.internaldepartmentmaster'),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_lcm_id',
            field=models.ForeignKey(blank=True, db_column='dem_lcm_id', help_text='Reference to Location Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_demands', to='hiringManagementTool.locationmaster'),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_lob_id',
            field=models.ForeignKey(blank=True, db_column='dem_lob_id', help_text='Reference to LOB Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lob_demands', to='hiringManagementTool.lobmaster'),
        ),
    ]
