# Generated by Django 4.2.11 on 2025-03-07 11:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0033_alter_opendemand_dem_idm_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_address',
            field=models.TextField(blank=True, help_text='Client Full Address', null=True),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_clientemail',
            field=models.EmailField(blank=True, help_text='Client Email Address', max_length=254, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_clientid',
            field=models.CharField(blank=True, help_text='Client unique ID (internal, manually inserted)', max_length=50, null=True, unique=True),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_clientphone',
            field=models.CharField(blank=True, help_text='Client Phone Number (e.g., +91-9988770098)', max_length=20, null=True),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_lcm_id',
            field=models.ForeignKey(blank=True, db_column='clm_lcm_id', help_text='Reference to Location Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_client', to='hiringManagementTool.locationmaster'),
        ),
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_managername',
            field=models.CharField(blank=True, help_text='Client Manager Name', max_length=50, null=True),
        ),
    ]
