# Generated by Django 4.2.11 on 2025-03-07 10:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0033_alter_opendemand_dem_idm_id_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CandidateDemandHistory',
            fields=[
                ('cdh_id', models.AutoField(help_text='Unique Candidate Demand History ID (Auto-generated)', primary_key=True, serialize=False)),
                ('cdh_insertdate', models.DateTimeField(auto_now_add=True, help_text='Record Creation Timestamp')),
                ('cdh_fromdata', models.JSONField(blank=True, help_text='Old Value/Data before change', null=True)),
                ('cdh_todata', models.JSONField(blank=True, help_text='New Value/Data after change', null=True)),
                ('cdh_cdm_id', models.ForeignKey(db_column='cdh_cdm_id', help_text='Reference to Open Demand', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_links', to='hiringManagementTool.candidatemaster')),
                ('cdh_csm_id', models.ForeignKey(blank=True, db_column='cdh_csm_id', help_text='Reference to Candidate Status Master', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='status_history', to='hiringManagementTool.candidatestatusmaster')),
                ('cdh_dem_id', models.ForeignKey(db_column='cdh_dem_id', help_text='Reference to Open Demand', on_delete=django.db.models.deletion.CASCADE, related_name='candidate_links', to='hiringManagementTool.opendemand')),
            ],
            options={
                'db_table': 'candidatedemandhistory',
                'managed': True,
            },
        ),
    ]
