# Generated by Django 5.1.5 on 2025-03-12 08:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0034_alter_clientmaster_clm_address_and_more'),
        ('hiringManagementTool', '0034_candidatedemandhistory'),
    ]

    operations = [
    ]
