# Generated by Django 4.2.11 on 2025-03-11 06:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0034_alter_clientmaster_clm_address_and_more'),
        ('hiringManagementTool', '0034_candidatedemandhistory'),
    ]

    operations = [
    ]
