# Generated by Django 4.2.11 on 2025-03-12 07:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0034_alter_clientmaster_clm_address_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendemand',
            name='dem_ctoolnumber',
            field=models.CharField(blank=True, help_text='Client Tool Number from Client', max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_lob_id',
            field=models.ForeignKey(db_column='dem_lob_id', help_text='Reference to LOB Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lob_demands', to='hiringManagementTool.lobmaster'),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_positions',
            field=models.IntegerField(default=0, help_text='Number of Positions Required'),
        ),
    ]
