# Generated by Django 5.1.5 on 2025-03-12 08:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0037_alter_demandstatusmaster_restricted_previous_statuses'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='demandstatusmaster',
            name='restricted_previous_statuses',
        ),
    ]
