# Generated by Django 5.1.5 on 2025-03-12 08:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0038_remove_demandstatusmaster_restricted_previous_statuses'),
    ]

    operations = [
        migrations.AddField(
            model_name='demandstatusmaster',
            name='restricted_previous_statuses',
            field=models.TextField(blank=True, db_column='restricted_previous_statuses', help_text='Comma-separated list of candidate status IDs that cannot transition to this status', null=True),
        ),
    ]
