# Generated by Django 5.1.5 on 2025-03-12 09:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0039_demandstatusmaster_restricted_previous_statuses'),
    ]

    operations = [
        migrations.RenameField(
            model_name='demandstatusmaster',
            old_name='restricted_previous_statuses',
            new_name='dsm_resstatus',
        ),
    ]
