# Generated by Django 5.1.5 on 2025-03-12 09:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0041_demandstatusmaster_dsm_inactive'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandstatusmaster',
            name='dsm_resstatus',
            field=models.TextField(blank=True, db_column='dsm_resstatus', help_text='Comma-separated list of demand status IDs that cannot transition to this status', null=True),
        ),
    ]
