# Generated by Django 5.1.5 on 2025-03-13 05:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0042_alter_demandstatusmaster_dsm_resstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatusmaster',
            name='dsm_inactive',
            field=models.BooleanField(db_column='dsm_inactive', default=False, help_text='If True (1), this status will not be listed in the application'),
        ),
    ]
