# Generated by Django 5.1.5 on 2025-03-13 05:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0044_remove_candidatestatusmaster_dsm_inactive_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatestatusmaster',
            name='csm_resstatus',
            field=models.TextField(blank=True, db_column='csm_resstatus', help_text='Comma-separated list of candidate status IDs that cannot transition to this status', null=True),
        ),
    ]
