# Generated by Django 5.1.5 on 2025-03-13 06:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0045_candidatestatusmaster_csm_resstatus'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemaster',
            name='cdm_comment',
            field=models.TextField(blank=True, help_text='Comment Entry', null=True),
        ),
    ]
