# Generated by Django 4.2.11 on 2025-03-19 07:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0035_alter_opendemand_dem_ctoolnumber_and_more'),
        ('hiringManagementTool', '0035_merge_20250311_1203'),
        ('hiringManagementTool', '0046_candidatemaster_cdm_comment'),
    ]

    operations = [
    ]
