# Generated by Django 4.2.11 on 2025-03-19 07:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0047_merge_20250319_1318'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendemand',
            name='dem_position_location',
            field=models.JSONField(blank=True, help_text='Position Location', null=True),
        ),
    ]
