# Generated by Django 4.2.11 on 2025-03-19 08:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0048_opendemand_dem_position_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendemand',
            name='dem_position_location',
        ),
        migrations.AddField(
            model_name='opendemand',
            name='dem_position_location',
            field=models.ManyToManyField(blank=True, help_text='Position Location', null=True, to='hiringManagementTool.locationmaster'),
        ),
    ]
