# Generated by Django 4.2.11 on 2025-03-19 08:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0049_remove_opendemand_dem_position_location_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendemand',
            name='dem_position_location',
        ),
    ]
