# Generated by Django 4.2.11 on 2025-03-19 09:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0051_opendemand_dem_position_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='opendemand',
            name='dem_position_location',
        ),
    ]
