# Generated by Django 4.2.11 on 2025-03-19 11:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0052_remove_opendemand_dem_position_location'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendemand',
            name='dem_position_location',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
