# Generated by Django 5.1.5 on 2025-03-20 09:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0053_opendemand_dem_position_location'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lobmaster',
            name='lob_description',
            field=models.TextField(blank=True, help_text='LOB Description', null=True),
        ),
    ]
