# Generated by Django 5.1.5 on 2025-03-20 11:33

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0054_alter_lobmaster_lob_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='locationmaster',
            name='lcm_insertdate',
            field=models.DateTimeField(default=django.utils.timezone.now, help_text='Record Creation Timestamp'),
        ),
    ]
