# Generated by Django 4.2.11 on 2025-03-22 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0055_locationmaster_lcm_insertdate'),
    ]

    operations = [
        migrations.AlterField(
            model_name='locationmaster',
            name='lcm_name',
            field=models.CharField(help_text='Location Manager Name', max_length=50, unique=True),
        ),
    ]
