# Generated by Django 4.2.11 on 2025-03-22 10:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0056_alter_locationmaster_lcm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='clientmaster',
            name='clm_name',
            field=models.CharField(help_text='Client Name', max_length=50, unique=True),
        ),
    ]
