# Generated by Django 5.1.5 on 2025-03-24 11:33

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0057_alter_clientmaster_clm_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employeemaster',
            name='emp_keyword',
            field=models.TextField(blank=True, help_text='Keywords to find specific requirements', null=True),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='emp_lcm_id',
            field=models.ForeignKey(blank=True, db_column='emp_lcm_id', help_text='Reference to Location Master Table', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='location_employee', to='hiringManagementTool.locationmaster'),
        ),
        migrations.AlterField(
            model_name='employeemaster',
            name='emp_phone',
            field=models.CharField(blank=True, help_text='Mobile or phone number (e.g., +91-9988770098)', max_length=20, null=True),
        ),
    ]
