# Generated by Django 4.2.11 on 2025-03-26 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0058_alter_employeemaster_emp_keyword_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='opendemand',
            name='dem_mandatoryskill',
            field=models.TextField(blank=True, help_text='Multiple mandatory skillsets separated by commas', null=True),
        ),
    ]
