# Generated by Django 4.2.11 on 2025-03-26 07:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0058_alter_employeemaster_emp_keyword_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewSchedulingTable',
            fields=[
                ('ist_id', models.AutoField(primary_key=True, serialize=False)),
                ('ist_interviewdate', models.DateField()),
                ('ist_interviewtime', models.TimeField()),
                ('ist_interviewtype', models.CharField(choices=[('Phone', 'Phone'), ('Video', 'Video'), ('On-site', 'On-site'), ('Other', 'Other')], max_length=50)),
                ('ist_interviewround', models.IntegerField()),
                ('ist_interviewername', models.CharField(max_length=255)),
                ('ist_intervieweremail', models.CharField(max_length=255)),
                ('ist_interviewstatus', models.CharField(choices=[('Scheduled', 'Scheduled'), ('Completed', 'Completed'), ('Cancelled', 'Cancelled'), ('Rescheduled', 'Rescheduled')], max_length=50)),
                ('ist_remarks', models.TextField(blank=True, null=True)),
                ('ist_createdate', models.DateTimeField(auto_now_add=True)),
                ('ist_updatedate', models.DateTimeField(auto_now=True)),
                ('ist_cdl', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hiringManagementTool.candidatedemandlink')),
            ],
        ),
    ]
