# Generated by Django 4.2.11 on 2025-03-26 07:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0059_interviewschedulingtable'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='interviewschedulingtable',
            options={'managed': True},
        ),
        migrations.AlterModelTable(
            name='interviewschedulingtable',
            table='interviewschedulingtable',
        ),
    ]
