# Generated by Django 4.2.11 on 2025-03-28 08:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0059_opendemand_dem_mandatoryskill'),
        ('hiringManagementTool', '0060_alter_interviewschedulingtable_options_and_more'),
    ]

    operations = [
    ]
