# Generated by Django 4.2.11 on 2025-04-04 10:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0064_interviewschedulingtable_ist_timezone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='demandhistory',
            name='dhs_fromdata',
            field=models.JSONField(blank=True, help_text='Old value/data before update', null=True),
        ),
        migrations.AlterField(
            model_name='demandhistory',
            name='dhs_todata',
            field=models.JSONField(blank=True, help_text='New value/data after update', null=True),
        ),
        migrations.AlterField(
            model_name='interviewschedulingtable',
            name='ist_timezone',
            field=models.CharField(default='UTC', help_text='Enter the time zone for the interview (e.g., Asia/Kolkata (IST)).', max_length=50),
        ),
    ]
