# Generated by Django 4.2.11 on 2025-04-08 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0065_alter_demandhistory_dhs_fromdata_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='candidatemaster',
            name='cdm_image',
            field=models.ImageField(blank=True, help_text='Candidate image', null=True, upload_to='candidate_images/'),
        ),
        migrations.AddField(
            model_name='clientmaster',
            name='clm_logo',
            field=models.ImageField(blank=True, help_text='Client Logo', null=True, upload_to='client_logos/'),
        ),
        migrations.AddField(
            model_name='employeemaster',
            name='emp_image',
            field=models.ImageField(blank=True, help_text='Employee image', null=True, upload_to='employee_images/'),
        ),
    ]
