# Generated by Django 4.2.11 on 2025-04-08 11:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0066_candidatemaster_cdm_image_clientmaster_clm_logo_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='candidatemaster',
            name='cdm_profile',
            field=models.FileField(blank=True, help_text='Candidate profile file (resume)', null=True, upload_to='candidate_profiles/'),
        ),
        migrations.AlterField(
            model_name='opendemand',
            name='dem_jd',
            field=models.FileField(blank=True, help_text='Job Description File Upload', null=True, upload_to='jd_files/'),
        ),
    ]
