# Generated by Django 4.2.11 on 2025-04-24 06:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hiringManagementTool', '0067_alter_candidatemaster_cdm_profile_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='opendemand',
            name='dem_position_location',
            field=models.JSONField(blank=True, default=list, null=True),
        ),
    ]
